#ifndef RTK_DECODER_VERSION_H
#define RTK_DECODER_VERSION_H

#define COMPONENT_VERSION_MAJOR    1
#define COMPONENT_VERSION_MINOR    1
#define COMPONENT_VERSION_REVISION 2
#define COMPONENT_VERSION_STEP     0

#endif
